# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: CD

pr: none

trigger:
  branches:
    include:
      - master

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: CD
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "14.x"

      - script: npm install
        displayName: "Install dependencies"

      - script: npm test
        displayName: "Run unit tests"

      - script: npm run build:frontend
        displayName: "Build the frontend templates with EJS"

      - script: npm run gen-artifact
        displayName: "Generate app artifact"

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: app

      - script: echo "deploying to acceptance"
        displayName: "Deploy to acceptance environment slot"

      - script: echo "e2e"
        displayName: "Exec e2e tests"

      - script: echo "Notify channels"
        displayName: "Notifying channels"

      - script: echo "deploying code to container"
        displayName: "Deploying app to production"
