version: "3.8"

services:
  blog-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - SERVER_PORT=8001
      - DATABASE_CONNECTIONSTRING=mongodb://mongo:27017/blog
      - NODE_ENV=production
    # command: npm run debug
  mongodb:
    image: mongo:4.4.1
    command: mongod --port 27018
    ports:
      - 27018:27018
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
