version: "3.8"

services:
  mongodb:
    container_name: blog_db
    image: mongo:4.4.1
    command: "mongod --port ${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  blog-backend:
    restart: always
    container_name: blog_nodejs
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SERVER_DEBUG_PORT}:${SERVER_DEBUG_PORT}"
    command: npm run start:backend
volumes:
  mongodb:
  mongodb_config:
