version: "3.8"

services:
  blog-backend:
    build:
      context: backend/.
    ports:
      - 8001:8001
      - 9229:9229
    environment:
      - SERVER_PORT=8001
      - DATABASE_CONNECTIONSTRING=mongodb://mongo:27017/blog
    volumes:
      - ./:/code
    command: npm run debug

  mongo:
    image: mongo:4.2.8
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  volumes:
    mongodb:
    mongodb_config:
