version: "3.8"

services:
  blog-backend:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8001:8001
      - 9229:9229
    environment:
      - SERVER_PORT=8001
      - DATABASE_CONNECTIONSTRING=mongodb://mongo:27017/blog
      - NODE_ENV=production
    # command: npm run debug
