# This is a basic workflow to help you get started with Actions

name: Continuous Integration / Continuous Delivery

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
#  pull_request:
#    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it - ACTION
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Instal dependencies
        run: npm install

      - name: Build project
        run: npm run build:frontend

      - name: Type check files
        run: npm run tsc

      - name: Lint check
        run: echo "npm lint"

      - name: Unit tests
        run: npm test

      - name: Integration tests
        run: echo "running integration tests"

      - uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: dist

      - name: Notify status
        run: echo "CI successful"

  CD:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: CI

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - uses: actions/download-artifact@v2
        with:
          name: app-artifact
          path: build

      - name: Structure of downloaded artifact
        run: ls -R
        working-directory: build

      - name: Notify status
        run: echo "CD successful"

      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
